#!/bin/sh /etc/rc.common

START=99

NAME=slowled
PROG=/usr/bin/slowLed

start() {
    if ! pgrep -f "$PROG" >/dev/null; then
        "$PROG" &
    fi
}

stop() {
    # Get the process ID of the slowled script
    local pid="$(pgrep -f "$PROG")"

    # If the script is running, kill it by its process ID
    if [ -n "$pid" ]; then
        kill "$pid"
    fi
}

restart() {
    stop

    # Wait for the process to stop
    while pgrep -f "$PROG" >/dev/null; do
        sleep 1
    done

    # Start the slowled script in the background
    start
    # Return success
    exit 0
}
